### PR TITLE
add my component

### PR DESCRIPTION
**Pull request by ElishevaAlshech**

### CODE REVIEW

**Comment by ElishevaAlshech** [comment]
please confirm my request

**Review by Rivki-Hayas — COMMENTED** [review]
yes i let you!!!!!!!!!!!!!!!!!!!!!!!

**Review by Rivki-Hayas — APPROVED** [review]
yyyeeyyyyy!!

**Review by Rivki-Hayas — DISMISSED** [review]
yyyy

**Review by sariHeber — APPROVED** [review]
excellent!!!

**Review by ElishevaAlshech — COMMENTED** [review]
aaaa

**Pull request merged**
